openapi: 3.1.0
info:
  title: watch-me
  version: '1.0'
  summary: インフルエンサーが告知をするプラットフォーム
  description: |-
    バックエンドgo
    フロントエンドnextで通信を行う際のapi
  contact:
    name: github
    url: SakaiTaka23
servers:
  - url: 'http://localhost:5000'
paths:
  /schedule:
    post:
      summary: post-schedule-create
      tags:
        - schedule
      responses:
        '200':
          description: 作成したスケジュールのidを返す
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: string
                properties:
                  id:
                    description: 作成したスケジュールのidを返す
                    type: string
                required:
                  - id
              examples:
                example-1:
                  value:
                    id: string
        '401':
          description: Unauthorized
      operationId: create-schedule
      description: 情報を元にスケジュールを新規作成する
      parameters: []
      security:
        - Firebase: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  about: string
                  emoji: string
                  date: '2019-08-24'
                  start_time: '14:15:22Z'
                  end_time: '14:15:22Z'
                  place: string
                  title: string
                  url: 'http://example.com'
              properties:
                about:
                  type: string
                  minLength: 1
                  maxLength: 250
                emoji:
                  type: string
                  minLength: 1
                  maxLength: 20
                start_time:
                  type: string
                  example: '2021-07-28T15:00'
                end_time:
                  type: string
                  example: '2021-07-28T15:00'
                place:
                  type: string
                  minLength: 1
                  maxLength: 50
                title:
                  type: string
                  minLength: 1
                  maxLength: 20
                url:
                  type: string
                  minLength: 1
                  format: uri
              required:
                - emoji
                - start_time
                - title
            examples:
              全ての要素がある場合:
                value:
                  about: string
                  emoji: string
                  start_time: '2021-07-28T15:00'
                  end_time: '2021-07-28T16:30'
                  place: string
                  title: string
                  url: 'http://example.com'
              最低限の要素のみの場合:
                value:
                  emoji: string
                  start_time: '2021-07-28T15:00'
                  title: string
        description: |-
          idを除いたスケジュールモデルを想定
          idはバックエンドで生成
          emojiに関しては作成時のフォームでは必須にはしない。埋められていない場合はフロントエンド側でランダムに一つ決めて送信する
  '/schedule/{user}/{schedule}':
    parameters:
      - schema:
          type: string
          minLength: 40
          maxLength: 40
        name: schedule
        in: path
        required: true
        description: スケジュールのuid
      - schema:
          type: string
        name: user
        in: path
        required: true
    delete:
      summary: delete schedule
      tags:
        - schedule
      responses:
        '200':
          description: 削除完了
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      operationId: delete-schedule-schedule
      description: |-
        スケジュールを消す
        今のところ既に削除されたものをリクエストしても200を返す
      security:
        - Firebase: []
      parameters:
        - schema:
            type: string
          in: header
          name: bearer
          description: firebase auth jwt
    get:
      summary: get schedule info
      operationId: get-schedule-schedule
      responses:
        '200':
          description: スケジュールモデル
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
              examples:
                example-1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    about: string
                    emoji: string
                    start_time: '2021-07-28T15:00'
                    end_time: '2021-07-28T15:00'
                    place: string
                    title: string
                    url: 'http://example.com'
                    user_id: a169451c-8525-4352-b8ca-070dd449a1a5
        '404':
          description: Not Found
      description: スケジュールの情報を取得する
      tags:
        - schedule
      security: []
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '409':
          description: 既にユーザー
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  id: string
                  name: string
              properties:
                name:
                  type: string
                  minLength: 1
            examples:
              メール・パスワード認証時:
                value:
                  name: string
              プロパイダ認証時:
                value: {}
        description: firebaseより得た要素を入れる
      description: |-
        ユーザーを新規登録

        ユーザーが既に存在している(uidが既に登録されている)場合409を返す

        ユーザーの初期値は「ユーザー+uid」
      parameters: []
      security:
        - Firebase: []
      tags:
        - user
    patch:
      summary: update user
      operationId: patch-user-update
      responses:
        '200':
          $ref: '#/components/responses/UserUpdateResult'
        '401':
          description: Unauthorized
        '409':
          description: 既に存在する名前が出たときにコンフリクト
      description: |
        ユーザーのスケジュールタイトル・名前の更新を行う
      security:
        - Firebase: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  name: string
                  schedule_title: string
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 30
                title:
                  type: string
                  minLength: 1
                  maxLength: 20
              required:
                - name
                - title
            examples:
              両方変更:
                value:
                  name: string
                  title: string
              名前のみを変更:
                value:
                  name: string
                  title: default value
        description: 両方を更新する場合片方を更新する場合どちらであっても両方の情報を送信する
      tags:
        - user
        - sns
  '/user/{title}/{year}/{month}':
    parameters:
      - schema:
          type: string
        name: title
        in: path
        required: true
        description: ユーザーのスケジュールのタイトル
      - schema:
          type: string
        name: year
        in: path
        required: true
        description: 検索する年
      - schema:
          type: string
        name: month
        in: path
        required: true
        description: 検索する月
    get:
      summary: Get User Schedule by User Title
      tags:
        - user
        - schedule
      responses:
        '200':
          $ref: '#/components/responses/UserSchedule'
        '404':
          description: Not Found
        '':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
              examples:
                example-1:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      about: string
                      emoji: string
                      start_time: '2021-07-28T15:00'
                      end_time: '2021-07-28T15:00'
                      place: string
                      title: string
                      url: 'http://example.com'
                      user_id: a169451c-8525-4352-b8ca-070dd449a1a5
          description: スケジュール一覧を返す
      operationId: get-user-username
      description: |-
        ユーザーのスケジュールタイトルからスケジュールを返す
        年・月をつけつけてその期間に始まるスケジュールのみ返す

        該当する値がない場合は空の配列を返す
      parameters: []
      security: []
  '/user/{schedule_title}/info':
    parameters:
      - schema:
          type: string
        name: schedule_title
        in: path
        required: true
    get:
      summary: user get info
      tags:
        - user
      responses:
        '200':
          $ref: '#/components/responses/UserInfoSimple'
        '404':
          description: Not Found
      operationId: get-user-username-info
      description: そのユーザーに関する基本的な情報を返す
      security: []
  '/user/{username}/unique':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
        description: ユーザー名
    get:
      summary: check unique username
      tags:
        - user
      responses:
        '200':
          description: 判定結果
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    result: bool
                properties:
                  result:
                    type: boolean
                required:
                  - result
              examples:
                'true':
                  value:
                    result: true
                'false':
                  value:
                    result: false
        '400':
          description: ユーザー名がない場合・長すぎる場合に返す
      operationId: get-user-username-unique
      description: |-
        ユーザー名を入れそのユーザー名が既に存在しているかどうかを判定し返す
        結果によらずステータスは200を返す
      security: []
components:
  schemas:
    Schedule:
      description: スケジュールに関する情報
      type: object
      x-examples:
        example-1:
          id: string
          about: string
          emoji: string
          date: string
          start_date: string
          end_date: string
          place: string
          title: string
          url: string
      examples:
        - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          about: string
          emoji: string
          start_time: '2021-07-28T15:00'
          end_time: '2021-07-28T15:00'
          place: string
          title: string
          url: 'http://example.com'
          user_id: a169451c-8525-4352-b8ca-070dd449a1a5
      x-tags:
        - schedule
      x-internal: false
      properties:
        id:
          type: string
          format: uuid
        about:
          type: string
          minLength: 1
        emoji:
          type: string
          minLength: 1
        start_time:
          type: string
          minLength: 1
          example: '11:00'
        end_time:
          type: string
          minLength: 1
          example: '17:00'
        place:
          type: string
          minLength: 1
        title:
          type: string
          minLength: 1
          maxLength: 20
        url:
          type: string
          minLength: 1
          format: uri
        user_id:
          type: string
          format: uuid
      required:
        - emoji
        - start_time
        - title
        - user_id
    SNS:
      description: snsの情報
      type: object
      x-examples:
        example-1:
          id: string
          url: string
      examples:
        - id: '1'
          url: 'http://example.com'
      x-tags:
        - sns
      properties:
        id:
          type: string
        url:
          type: string
          minLength: 1
          format: uri
      required:
        - id
        - url
    User:
      description: ユーザー情報
      type: object
      x-examples:
        example-1:
          id: string
          name: string
          schedule_title: string
      examples:
        - id: string
          name: string
          schedule_title: string
      x-tags:
        - user
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        schedule_title:
          type: string
          minLength: 1
      required:
        - id
        - name
        - schedule_title
  securitySchemes:
    Firebase:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ''
          refreshUrl: ''
          scopes: {}
      description: ''
  responses:
    UserUpdateResult:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                id: string
                name: string
                mail: string
                title: string
            properties:
              id:
                type: string
                minLength: 1
              name:
                type: string
                minLength: 1
              schedule_title:
                type: string
                minLength: 1
              sns:
                type: array
                items:
                  $ref: '#/components/schemas/SNS'
            required:
              - id
              - name
              - schedule_title
          examples:
            example-1:
              value:
                id: string
                name: string
                schedule_title: string
                sns:
                  - id: '1'
                    url: 'http://example.com'
    UserInfoSimple:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                id: string
                name: string
                schedule_title: string
                sns:
                  - id: '1'
                    url: 'http://example.com'
            properties:
              id:
                type: string
                minLength: 1
                format: uuid
              name:
                type: string
                minLength: 1
              schedule_title:
                type: string
                minLength: 1
              sns:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  $ref: '#/components/schemas/SNS'
            required:
              - id
              - name
              - schedule_title
              - sns
          examples:
            example-1:
              value:
                id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                name: string
                schedule_title: string
                sns:
                  - id: '1'
                    url: 'http://example.com'
    UserSchedule:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Schedule'
          examples:
            example-1:
              value:
                - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                  about: string
                  emoji: string
                  start_time: '2021-07-28T15:00'
                  end_time: '2021-07-28T15:00'
                  place: string
                  title: string
                  url: 'http://example.com'
                  user_id: a169451c-8525-4352-b8ca-070dd449a1a5
            example-2:
              value: []
  parameters:
    year:
      name: year
      in: query
      schema:
        type: number
        minLength: 2021
        maxLength: 2025
        minimum: 2021
        maximum: 2025
        example: 2021
      description: 検索したい年
      required: true
    month:
      name: month
      in: query
      required: true
      schema:
        type: number
        minLength: 1
        maxLength: 12
        minimum: 1
        maximum: 12
        example: 8
      description: 検索したい月
tags:
  - name: schedule
  - name: sns
  - name: user
